class Plant {
  String name;
  String price;
  String imgAsset;
  String rating;
  String size;
  String desc;

  Plant({
    required this.name,
    required this.price,
    required this.imgAsset,
    required this.rating,
    required this.size,
    required this.desc,
  });
}

var aloevera = [
  Plant(
    name: 'Aloe Vera Av',
    price: '45.000',
    imgAsset: 'images/aloevera-1.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Aloe Vera tipe Av sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Bv',
    price: '40.000',
    imgAsset: 'images/aloevera-2.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Aloe Vera tipe Bv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Cv',
    price: '35.000',
    imgAsset: 'images/aloevera-3.jpg',
    rating: '4.5',
    size: 'small',
    desc: 'Aloe Vera tipe Cv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Dv',
    price: '50.000',
    imgAsset: 'images/aloevera-4.jpg',
    rating: '4.5',
    size: 'large',
    desc: 'Aloe Vera tipe Dv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Av',
    price: '45.000',
    imgAsset: 'images/aloevera-1.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Aloe Vera tipe Av sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Bv',
    price: '40.000',
    imgAsset: 'images/aloevera-2.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Aloe Vera tipe Bv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Cv',
    price: '35.000',
    imgAsset: 'images/aloevera-3.jpg',
    rating: '4.5',
    size: 'small',
    desc: 'Aloe Vera tipe Cv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Dv',
    price: '50.000',
    imgAsset: 'images/aloevera-4.jpg',
    rating: '4.5',
    size: 'large',
    desc: 'Aloe Vera tipe Dv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Av',
    price: '45.000',
    imgAsset: 'images/aloevera-1.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Aloe Vera tipe Av sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Bv',
    price: '40.000',
    imgAsset: 'images/aloevera-2.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Aloe Vera tipe Bv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Cv',
    price: '35.000',
    imgAsset: 'images/aloevera-3.jpg',
    rating: '4.5',
    size: 'small',
    desc: 'Aloe Vera tipe Cv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Aloe Vera Dv',
    price: '50.000',
    imgAsset: 'images/aloevera-4.jpg',
    rating: '4.5',
    size: 'large',
    desc: 'Aloe Vera tipe Dv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
];

var cactus = [
  Plant(
    name: 'Cactus Av',
    price: '50.000',
    imgAsset: 'images/cactus-1.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Cactus tipe Av sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Bv',
    price: '70.000',
    imgAsset: 'images/cactus-2.jpg',
    rating: '4.5',
    size: 'large',
    desc: 'Cactus tipe Bv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Cv',
    price: '35.000',
    imgAsset: 'images/cactus-3.jpg',
    rating: '4.5',
    size: 'small',
    desc: 'Cactus tipe Cv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Dv',
    price: '50.000',
    imgAsset: 'images/cactus-4.jpg',
    rating: '4.5',
    size: 'medium', 
    desc: 'Cactus tipe Dv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Av',
    price: '50.000',
    imgAsset: 'images/cactus-1.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Cactus tipe Av sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Bv',
    price: '70.000',
    imgAsset: 'images/cactus-2.jpg',
    rating: '4.5',
    size: 'large',
    desc: 'Cactus tipe Bv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Cv',
    price: '35.000',
    imgAsset: 'images/cactus-3.jpg',
    rating: '4.5',
    size: 'small',
    desc: 'Cactus tipe Cv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Dv',
    price: '50.000',
    imgAsset: 'images/cactus-4.jpg',
    rating: '4.5',
    size: 'medium', 
    desc: 'Cactus tipe Dv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Av',
    price: '50.000',
    imgAsset: 'images/cactus-1.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Cactus tipe Av sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Bv',
    price: '70.000',
    imgAsset: 'images/cactus-2.jpg',
    rating: '4.5',
    size: 'large',
    desc: 'Cactus tipe Bv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Cv',
    price: '35.000',
    imgAsset: 'images/cactus-3.jpg',
    rating: '4.5',
    size: 'small',
    desc: 'Cactus tipe Cv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Cactus Dv',
    price: '50.000',
    imgAsset: 'images/cactus-4.jpg',
    rating: '4.5',
    size: 'medium', 
    desc: 'Cactus tipe Dv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
];

var monstera = [
  Plant(
    name: 'Monstera Av',
    price: '50.000',
    imgAsset: 'images/monstera-1.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Monstera tipe Av sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Bv',
    price: '40.000',
    imgAsset: 'images/monstera-2.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Monstera tipe Bv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Cv',
    price: '35.000',
    imgAsset: 'images/monstera-3.jpg',
    rating: '4.5',
    size: 'small',
    desc: 'Monstera tipe Cv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Dv',
    price: '50.000',
    imgAsset: 'images/monstera-4.jpg',
    rating: '4.5',
    size: 'large',
    desc: 'Monstera tipe Dv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Av',
    price: '50.000',
    imgAsset: 'images/monstera-1.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Monstera tipe Av sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Bv',
    price: '40.000',
    imgAsset: 'images/monstera-2.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Monstera tipe Bv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Cv',
    price: '35.000',
    imgAsset: 'images/monstera-3.jpg',
    rating: '4.5',
    size: 'small',
    desc: 'Monstera tipe Cv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Dv',
    price: '50.000',
    imgAsset: 'images/monstera-4.jpg',
    rating: '4.5',
    size: 'large',
    desc: 'Monstera tipe Dv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Av',
    price: '50.000',
    imgAsset: 'images/monstera-1.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Monstera tipe Av sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Bv',
    price: '40.000',
    imgAsset: 'images/monstera-2.jpg',
    rating: '4.5',
    size: 'medium',
    desc: 'Monstera tipe Bv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Cv',
    price: '35.000',
    imgAsset: 'images/monstera-3.jpg',
    rating: '4.5',
    size: 'small',
    desc: 'Monstera tipe Cv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
  Plant(
    name: 'Monstera Dv',
    price: '50.000',
    imgAsset: 'images/monstera-4.jpg',
    rating: '4.5',
    size: 'large',
    desc: 'Monstera tipe Dv sangat cocok untuk menambah koleksi bunga-bunga anda!',
  ),
];
